---
- hosts: localhost
  gather_facts: false
  vars:
    all_hosts: "{{ groups['cluster_batch'] + groups['cluster_login'] }}"
  tasks:

    - name: Wait for SSH access to proxy host
      wait_for:
        host: "{{ ohpc_proxy_address }}"
        port: 22
        state: started
        timeout: 120
      delegate_to: "localhost"

    - name: Scan for SSH keys
      command: "ssh {{ ansible_user }}@{{ ohpc_proxy_address }} ssh-keyscan -t rsa {{ hostvars[item]['ansible_host'] }}"
      register: keyscan_results
      changed_when: False
      delegate_to: "localhost"
      loop: "{{ all_hosts }}"

    - name: Ensure servers are in SSH known hosts
      blockinfile:
        block: |
          {% for key in item.stdout_lines %}
          {{ key }}
          {% endfor %}
        create: true
        marker: "# {mark} MANAGED BLOCK FOR OpenHPC.{{ index }}"
        path: "~/.ssh/known_hosts"
      loop: "{{ keyscan_results['results'] }}"
      loop_control:
        index_var: index

- hosts:
  - cluster_login
  - cluster_control
  - cluster_batch
  become: yes
  vars:
    openhpc_repo_url: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
  pre_tasks:
    - name: Generate /etc/hosts file content
      set_fact:
        etc_hosts_content: |
          {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
          {% endfor %}
      run_once: true
    - name: Create entries in /etc/hosts for all nodes
      blockinfile:
        path: /etc/hosts
        create: no
        state: present
        block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"
    - name: Install OpenHPC repository
      yum:
        name: "{{ openhpc_repo_url }}"
        state: present
    - name: Install software collections and epel
      yum:
        name: ["centos-release-scl", "epel-release"]
        state: present
    - name: update packages
      yum:
        name: '*'
        state: latest
      register: update_packages
    - name: reboot if there are updates
      reboot:
      when: update_packages is changed
  roles:
    - role: stackhpc.openhpc
      openhpc_enable:
        control: "{{ inventory_hostname in groups['cluster_control'] }}"
        batch: "{{ inventory_hostname in groups['cluster_batch'] }}"
        runtime: true
      openhpc_slurm_service_enabled: true
      openhpc_slurm_control_host: "{{ groups['cluster_control'] | first }}"
      openhpc_slurm_partitions:
        - name: "compute"
          num_nodes: "{{ groups['cluster_batch'] | length + 1 }}"
          user: "centos"
      openhpc_cluster_name: ohpc
      openhpc_packages:
        - infiniband-diags

- hosts:
  - cluster_login
  become: yes
  roles:
    - role: ansible-role-ood
      public_url: "{{ ohpc_proxy_address }}"
      cluster_name: ohpc
      host_regex: ohpc-compute-\d+

- hosts:
  - cluster_batch
  become: yes
  roles:
    - role: ood-compute
