# This only DEPLOYS the reimaging tools. To use them see the README.

- hosts:
  - localhost
  tasks:
  - name: Create a key
    openssh_keypair:
      path: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
  - name: Add to authorized keys
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage.pub') }}"
  - name: Create ansible/tf control host reimage script
    template:
        src: "{{ playbook_dir }}/slurmscripts/reconfigure.j2"
        dest: "{{ playbook_dir }}/slurmscripts/reconfigure.py"
        owner: centos
        mode: 0744

- hosts: cluster_batch
  tasks:
    - name: get deployment user name
      become: false
      local_action: command whoami
      register: ansible_host_whoami
      run_once: true
      changed_when: false
    - set_fact: ansible_host_username="{{ansible_host_whoami.stdout_lines[0]}}"
      run_once: true
      changed_when: false
    - name: Copy private key to compute nodes
      copy:
        src: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
        dest: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
        mode: "0400"
    - name: Create reboot script on compute nodes
      template:
        src: slurmscripts/reboot.j2
        dest: /etc/slurm/reboot.sh
        owner: root
        mode: u=rwx,g=rx,o=rx
      become: yes
