- hosts:
  - cluster_control
  #- cluster_batch
  tasks:
    - name: Deploy slurm reimage job script
      template:
        src: "{{ playbook_dir }}/slurmscripts/runreimage.j2"
        dest: "/home/{{ ansible_user }}/runreimage.sh"
      # note this doesn't need to be on the compute node, or to be u+x, but as it's not in a shared dir
      # we won't see output!
  
- hosts:
  - localhost
  vars:
    venv: "{{ playbook_dir }}/.venv/bin/activate"
    tf_compute_resource: "openstack_compute_instance_v2" # terraform "resource type" of compute instances
    tf_lock_timeout: 240 # number of seconds to retry terraform operations if state file locked
  tasks:
  - name: Create a key
    openssh_keypair:
      path: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
  - name: Add to authorized keys
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage.pub') }}"
  - name: Create ansible/tf control host reimage script
    template:
        src: "{{ playbook_dir }}/slurmscripts/reimage.j2"
        dest: "{{ playbook_dir }}/slurmscripts/reimage.py"
        owner: centos
        mode: 0744

- hosts: cluster_batch
  tasks:
    - name: Copy private key to compute nodes
      copy:
        src: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
        dest: "/home/{{ ansible_user }}/.ssh/id_ssh_rsa_reimage"
        mode: "0400"
