venv: "{{ playbook_dir }}/.venv/bin/activate"
tf_compute_resource: "openstack_compute_instance_v2" # terraform "resource type" of compute instances
tf_lock_timeout: 240 # number of seconds to retry terraform operations if state file locked
